spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to MyBank Accounts API Service - QA Environment"
  contactDetails:
    name: "Kousik Das"
    email: "kousik.das2223@gmail.com"
  supportNumbers:
    - 777-555-5555
    - 888-666-6666